# Generated by Django 5.2.5 on 2025-08-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name="Номер телефона"),
        ),
    ]
