# Generated by Django 5.2.5 on 2025-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(blank=True, null=True, verbose_name="ID чата в Телеграм"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tg_username",
            field=models.CharField(blank=True, null=True, verbose_name="Имя пользователя в Телеграм"),
        ),
    ]
