# Generated by Django 5.2.5 on 2025-08-21 19:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=30, verbose_name="Место")),
                ("scheduled_time", models.TimeField(verbose_name="Время")),
                ("action", models.CharField(max_length=60, verbose_name="Действие")),
                ("is_enjoyable", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("period", models.DurationField(default=datetime.timedelta(days=1), verbose_name="Периодичность")),
                ("reward", models.CharField(blank=True, max_length=60, null=True, verbose_name="Вознаграждение")),
                (
                    "action_time",
                    models.DurationField(default=datetime.timedelta(seconds=900), verbose_name="Время на выполнение"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="Признак публичности")),
                (
                    "habit_reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits_rewarded",
                        to="tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
