# Generated by Django 5.2.5 on 2025-08-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="action_time",
            new_name="duration",
        ),
    ]
