# Generated by Django 5.2.5 on 2025-08-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_rename_action_time_habit_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
