# Generated by Django 5.2.5 on 2025-08-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_habit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["action"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
